<a href="https://colab.research.google.com/github/swarubm/pythonreview/blob/main/NUMPY_OPERATIONS%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

# DIMENSION

In [5]:
 arr.ndim

1

# TO FIND DIMENSION

In [6]:
a = ([[1,2,3],[4,5,6]])
a = np.array(a)
a.ndim


2

# TO FIND SHAPE OF AN ARRAY

In [7]:
a = ([[1,2,3],[4,5,6]])
a = np.array(a)
a.shape

(2, 3)

In [8]:
a = ([[[[[[[                  ]]]]]]])
a = np.array(a)
a.ndim
a.shape

(1, 1, 1, 1, 1, 1, 0)

# arange

In [9]:
range = np.arange(10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
range = np.arange(1,10,2)        #(start,stop,step)
range                             #start inclusive and stop exvlusive

array([1, 3, 5, 7, 9])

# linspace    

In [11]:
arr = np.linspace(1,10,5)  #(start,stop,step)
arr                        #from 1 to 10 it divides that range to 5 equal parts

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Logspace

In [12]:
arr = np.logspace(1,4,3)   #(start,stop,step)
arr                        #10power1  to   10power4      how evenly interval values we wanted 10 316 1000  are 3 intervals

array([   10.        ,   316.22776602, 10000.        ])

# zeros

In [13]:
arr = np.zeros(5) #CREATE ARRAY WITH THAT MUCH OF ZEROES
arr

array([0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros ([2,4,5]) #2=no of block
arr                      #4=no of rows
                        #5=no o colms

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
arr = np.ones([4,2])   #row and cols
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Full

In [16]:
arr = np.full([2,4],7)     #([row,col],value point)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

# empty

In [17]:
arr = np.empty([2,3])
arr

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

# random.rand()

In [18]:
arr = np.random.rand(2,4)   #it gives random float points
arr                          #pass function without []  not list

array([[0.12713875, 0.23222222, 0.11848841, 0.90404322],
       [0.99166225, 0.01969889, 0.70769783, 0.73790247]])

In [19]:
np.random.randn(2,3)          #random floats from normal or gauss distrbtn
arr                            #n

array([[0.12713875, 0.23222222, 0.11848841, 0.90404322],
       [0.99166225, 0.01969889, 0.70769783, 0.73790247]])

In [20]:
arr = np.random.randint(10,100)    #(start,stop) range for random int
arr

78

In [21]:
arr = np.random.randint(10,100,size = (2,3))  #adding size to get ranged numbers
arr

array([[39, 77, 26],
       [67, 80, 50]])

# NUMPY DATA TYPES AND TYPE CASTING

In [22]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [23]:
print(type(arr))

<class 'numpy.ndarray'>


In [24]:
lst = ["string",1,2,3.1,4]
arr = np.array(lst)
arr

array(['string', '1', '2', '3.1', '4'], dtype='<U32')

In [25]:
arr.dtype

dtype('<U32')

In [26]:
arr = np.array([1,2,3,4],dtype = np.int64)
arr

array([1, 2, 3, 4])

# TYPECASTING

In [27]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [28]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [29]:
new_arr.dtype

dtype('float64')

In [30]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

#Typecasting error

In [31]:
arr = np.array(["1","2","hello"])      #we cant convert str to int
arr2 = arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

In [32]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr.shape

(2, 3)

In [34]:
arr.ndim

2

In [35]:
arr.size   #total no of elements in the array

6

In [36]:
arr.itemsize           #8bit of storage

8

# RESHAPE

In [37]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)         #convert it to 2 row and 3 cols
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [38]:
reshape2 = reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Ravel

In [39]:
ravel = reshape2.ravel()    #convert to 1d array
ravel

array([1, 2, 3, 4, 5, 6])

In [40]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


# flatten

In [41]:
flat = reshape2.flatten()  #also used to convert 1d array
flat

array([100,   2,   3,   4,   5,   6])

In [42]:
flat[0] = 1
flat

array([1, 2, 3, 4, 5, 6])

In [43]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

# Arithmetic operations

In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [45]:
#addition
print(a+b)

[5 7 9]


In [46]:
#diff
print(a-b)

[-3 -3 -3]


In [47]:
#div
print(a/b)

[0.25 0.4  0.5 ]


In [48]:
#intdiv             #integer division
print(b//a)

[4 2 2]


In [49]:
#mul
print(a*b)

[ 4 10 18]


In [50]:
#mod
print(b%a)

[0 1 0]


In [51]:
#pow
print(a**2)

[1 4 9]


# UNIVERSAL FUNCTION

In [52]:
arr = np.array([1,4,9,16])

# square root

In [53]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


# exponential

In [54]:
print(np.exp(arr))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [55]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


#sin function

In [56]:
angles = np.array([0,np.pi,np.pi/2])     #sin(0),sin(pi),sin(pi/2) values
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


# INDEXING AND SLICING

In [57]:
a = [1,2,3,4,5]

In [58]:
a[-1:-4:-1]

[5, 4, 3]

In [59]:
a[::2]

[1, 3, 5]

In [60]:
arr = np.array([10,20,30,40,50])
         # index  0,1,2,3,4
arr[::2]

array([10, 30, 50])

In [61]:
print(arr[-1])

50


# md   array

In [62]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [63]:
print(matrix[0:2,:])

[[1 2 3]
 [4 5 6]]


In [64]:
print(matrix[1:,1:])           #access row and cols

[[5 6]
 [8 9]]


# index arrays

In [65]:
arr = np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


# Iterating with nditer()

In [66]:
arr = np.array([[1,2],[3,4]])

In [67]:
for x in np.nditer(arr):
  print(x,end = " ")             #elements

1 2 3 4 

In [68]:
for ind, x in np.ndenumerate(arr):           #to know index and value
   print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


# views vs copies

In [69]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [70]:
view[0]=200
view

array([200,   3])

In [71]:
arr

array([  1, 200,   3,   4,   5])

# copy

In [72]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [73]:
copy[0] = 2
copy

array([2, 3])

In [74]:
arr

array([  1, 200,   3,   4,   5])

# TRANSPOASE

In [75]:
arr = np.array([[1,2],[3,4]])   #row is converted to col viceversa
arr

array([[1, 2],
       [3, 4]])

In [76]:
print(arr.transpose())

[[1 3]
 [2 4]]


# swapaxes

In [77]:
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [78]:
swap = np.swapaxes(arr,0,1)  #swap oth axes with first axes
swap.shape

(2, 1, 2)

In [79]:
swap

array([[[1, 2]],

       [[3, 4]]])

# concatenation

In [80]:
a  = np.array([[1,2]])
b  = np.array([[5,6]])

In [81]:
combine = np.concatenate((a,b))
combine

array([[1, 2],
       [5, 6]])

In [82]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [83]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [86]:
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


## axis =0 means rows
## axis =1 means cols

In [89]:
print(np.stack((arr1,arr2),axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
print(np.stack((arr1,arr2),axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [96]:
arr1

array([[1, 2],
       [3, 4]])

In [95]:
print(np.split(arr1, 2))

[array([[1, 2]]), array([[3, 4]])]


In [97]:
print(np.hsplit(arr1,2))

[array([[1],
       [3]]), array([[2],
       [4]])]


# Repeat

In [98]:
arr = np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


# Tile

In [100]:
print(np.tile(arr,2))

[1 2 3 1 2 3]


# Agregate function

In [102]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [103]:
np.mean(arr)

np.float64(3.0)

In [104]:
np.median(arr)

np.float64(3.0)

In [105]:
np.std(arr)

np.float64(1.4142135623730951)

In [106]:
np.min(arr)

np.int64(1)

In [107]:
np.max(arr)

np.int64(5)

In [108]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
print(np.sum(matrix,axis = 0))

[12 15 18]


# cumulative operation - running total

In [110]:
arr

array([1, 2, 3, 4, 5])

In [113]:
print(np.cumsum(arr))     #sum of first and scond element
                           #sum of first,second and third element
                           #sum of first,second,third and fourth element
                           #sum of first,second,third,fourth and fifth element

[ 1  3  6 10 15]


In [114]:
print(np.cumprod(arr))     #one*1
                           #one*2
                           #one*2*3
                           #one*2*3*4
                           #one*2*3*4*5


[  1   2   6  24 120]


# Conditional based choices

In [118]:
arr

array([1, 2, 3, 4, 5])

In [117]:
result = np.where(arr< 2,"low","high")
result

array(['low', 'high', 'high', 'high', 'high'], dtype='<U4')

# argwhere: row:col position for 2d arrays

In [119]:
arr

array([1, 2, 3, 4, 5])

In [121]:
print(np.argwhere(arr>2))

[[2]
 [3]
 [4]]


In [127]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
print(np.argwhere(matrix>5))   #wherever  index >5  [1 2]  first row 2nd cols

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


# logical and

In [129]:
arr

array([10, 20, 30, 40, 50])

In [130]:
mask = np.logical_and(arr>15,arr<35)        #condition
mask

array([False,  True,  True, False, False])

In [131]:
arr[mask]

array([20, 30])

# logical or

In [136]:
mask = np.logical_or(arr>60,arr<35)
arr[mask]

array([10, 20, 30])

In [141]:
arr2 = np.array([0,1,5,0,5])
arr2

array([0, 1, 5, 0, 5])

In [142]:
print(np.nonzero(arr2))  # it will print non zero elment arra INDEX

(array([1, 2, 4]),)


# Broadcasting

In [148]:
image = np.array([[200,150],[100,250]])
image.shape


(2, 2)

In [149]:
image

array([[200, 150],
       [100, 250]])

In [146]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

# VECTORIZATION

In [151]:
np.vectorize()   #convert regular functn to be applied on an array

In [152]:
def square(x):
  return x*x
  vfunc = np.vectorize(square)

In [153]:
arr

array([10, 20, 30, 40, 50])

# DEALING WITH MISSNG VALUES
#np.nan-----> NOT A NUMBER

In [154]:
a = np.array([1,2,np.nan,4])

In [155]:
a

array([ 1.,  2., nan,  4.])

# np.inf    -------> +ve and-ve infinites

In [157]:
#np.isnan
#np.isinf
#np.isinfinite

In [158]:
a

array([ 1.,  2., nan,  4.])

In [160]:
print(np.isnan(a))

[False False  True False]


In [162]:
b = np.array([1,np.nan,np.inf,10.2,40])

In [163]:
print(np.isinf(b))

[False False  True False False]


In [167]:
new_b=np.nan_to_num(b)    #remove not a nan/infinite values

In [169]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])